
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:80"
    networks:
      - juca_backend-network

networks:
  juca_backend-network:
    driver: bridge
