<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use \App\Models\Project;
class ProjectsTableSeeder extends Seeder


{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      
       Project::create([
      
        'name'=>'ToDoList',
        'description'=>'Aplication to check homeworks',
        'images'=>json_encode([
            '/apibackend/public/images/react.png',
            '/apibackend/public/images/reactToDo/start.png',
            '/apibackend/public/images/reactToDo/modal.png',
              '/apibackend/public/images/reactToDo/todo.png',
          ]),
        'language'=>'React'

       ]);

       Project::create([
      
        'name'=>'PyGame',
        'description'=>'A game about a warrior flingging fire balls',
        'images'=>json_encode([
            '/apibackend/public/images/python.png',
            '/apibackend/public/images/python/ole.png',
            '/apibackend/public/images/python/levels.png',
              '/apibackend/public/images/python/game.png',
            ]),
        'language'=>'Python'

       ]);
       Project::create([
      
        'name'=>'Transmilenio',
        'description'=>'Simple console aplication about routes and travels on the city',
        'images'=>json_encode([

            '/apibackend/public/images/java.png',
        '/apibackend/public/images/java/welcome.png',
        '/apibackend/public/images/java/routes.png',
          '/apibackend/public/images/java/map.png',
        '/apibackend/public/images/java/pay.png',
    '/apibackend/public/images/java/ticket.png' ]),
        'language'=>'Java'

       ]);
       Project::create([
      
        'name'=>'CodinkGame',
        'description'=>'A game to check the code generated by the machine',
        'images'=>json_encode(['/apibackend/public/images/vue.png','/apibackend/public/images/vue.png']),
        'language'=>'Vue'

       ]);
       
       
       ;
    }
}
